In [68]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as mlp

In [69]:
df = pd.read_csv('climate_change_dataset.csv')
df

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
0,2006,UK,8.9,9.3,3.1,1441,530911230,20.4,14,59.8
1,2019,USA,31.0,4.8,4.2,2407,107364344,49.2,8,31.0
2,2014,France,33.9,2.8,2.2,1241,441101758,33.3,9,35.5
3,2010,Argentina,5.9,1.8,3.2,1892,1069669579,23.7,7,17.7
4,2007,Germany,26.9,5.6,2.4,1743,124079175,12.5,4,17.4
...,...,...,...,...,...,...,...,...,...,...
995,2019,India,23.6,8.0,1.2,1365,1358019778,10.0,8,20.2
996,2000,UK,21.8,10.0,2.2,1273,876123161,14.9,14,30.1
997,2019,Argentina,23.8,8.9,4.7,891,1120533308,25.9,10,46.5
998,2016,Australia,21.0,14.9,3.1,1136,380662109,24.5,3,44.5
999,2011,Germany,24.1,17.3,2.1,2854,398407112,41.0,3,19.8

In [70]:
df.size

10000

In [71]:
df.shape

(1000, 10)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         1000 non-null   int64
 1   Country                      1000 non-null   object
 2   Avg Temperature (°C)         1000 non-null   float64
 3   CO2 Emissions (Tons/Capita)  1000 non-null   float64
 4   Sea Level Rise (mm)          1000 non-null   float64
 5   Rainfall (mm)                1000 non-null   int64
 6   Population                   1000 non-null   int64
 7   Renewable Energy (%)         1000 non-null   float64
 8   Extreme Weather Events       1000 non-null   int64
 9   Forest Area (%)              1000 non-null   float64
dtypes: float64(5), int64(4), object(1)
memory usage: 78.3+ KB

In [73]:
df.describe()

,Year,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000
mean,2011.432000,19.883100,10.425800,3.009600,1738.761000,7.053830e+08,27.300500,7.291000,40.572000
std,7.147199,8.542897,5.614665,1.146081,708.976616,4.093910e+08,12.970808,4.422655,17.398998
min,2000.000000,5.000000,0.500000,1.000000,501.000000,3.660891e+06,5.100000,0.000000,10.100000
25%,2005.000000,12.175000,5.575000,2.000000,1098.750000,3.436242e+08,16.100000,3.000000,25.600000
50%,2012.000000,20.100000,10.700000,3.000000,1726.000000,7.131166e+08,27.150000,8.000000,41.150000
75%,2018.000000,27.225000,15.400000,4.000000,2362.500000,1.073868e+09,38.925000,11.000000,55.800000
max,2023.000000,34.900000,20.000000,5.000000,2999.000000,1.397016e+09,50.000000,14.000000,70.000000

In [74]:
df.isnull().sum()

Year                           0
Country                        0
Avg Temperature (°C)           0
CO2 Emissions (Tons/Capita)    0
Sea Level Rise (mm)            0
Rainfall (mm)                  0
Population                     0
Renewable Energy (%)           0
Extreme Weather Events         0
Forest Area (%)                0
dtype: int64

In [75]:
df.head()

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
0,2006,UK,8.9,9.3,3.1,1441,530911230,20.4,14,59.8
1,2019,USA,31.0,4.8,4.2,2407,107364344,49.2,8,31.0
2,2014,France,33.9,2.8,2.2,1241,441101758,33.3,9,35.5
3,2010,Argentina,5.9,1.8,3.2,1892,1069669579,23.7,7,17.7
4,2007,Germany,26.9,5.6,2.4,1743,124079175,12.5,4,17.4

In [76]:
df.tail()

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
995,2019,India,23.6,8.0,1.2,1365,1358019778,10.0,8,20.2
996,2000,UK,21.8,10.0,2.2,1273,876123161,14.9,14,30.1
997,2019,Argentina,23.8,8.9,4.7,891,1120533308,25.9,10,46.5
998,2016,Australia,21.0,14.9,3.1,1136,380662109,24.5,3,44.5
999,2011,Germany,24.1,17.3,2.1,2854,398407112,41.0,3,19.8

In [77]:
df[df['Population']==df['Population'].max()]

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
700,2007,Russia,24.9,12.4,4.3,1450,1397016073,39.7,12,66.5

In [78]:
top_country = df.sort_values(by='Population',ascending=False).drop_duplicates().head(10)
top_country

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
700,2007,Russia,24.9,12.4,4.3,1450,1397016073,39.7,12,66.5
37,2019,Canada,21.8,1.0,4.9,2524,1395185778,5.8,1,51.0
341,2016,Brazil,28.1,16.9,4.9,934,1393981934,26.9,12,43.3
622,2017,Canada,16.3,2.3,3.4,2458,1391480145,17.1,9,63.9
344,2020,Brazil,14.1,3.3,2.1,1573,1391047250,31.1,5,26.3
960,2010,Mexico,31.0,16.6,2.9,1532,1388289771,48.9,8,40.8
456,2000,Australia,11.4,2.2,1.8,1071,1388230143,12.0,4,50.9
595,2022,UK,7.5,19.2,3.3,1045,1387457528,44.7,13,31.1
273,2002,Canada,18.3,11.5,3.5,2538,1386998486,21.0,11,12.3
805,2017,Japan,29.8,1.9,1.6,1073,1385374585,39.4,8,28.3

In [79]:
df.duplicated().sum()

np.int64(0)

In [80]:
df.duplicated('Country').value_counts()

True     985
False     15
Name: count, dtype: int64

In [81]:
df[df['Country']=='India']['Population'].sum()

np.int64(45963624659)

In [82]:
df.duplicated('Year').value_counts()

True     976
False     24
Name: count, dtype: int64

In [83]:
df[df['Country'] == 'India']

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
15,2023,India,31.0,17.6,2.0,2444,365927452,25.1,8,20.6
22,2005,India,7.7,6.1,4.0,1219,588745515,21.3,9,21.7
25,2000,India,20.9,15.9,2.6,1100,1237433800,26.4,8,61.3
46,2003,India,18.9,19.0,4.4,1990,322675191,43.3,12,11.5
52,2019,India,27.7,5.1,4.5,2273,1097734281,5.9,13,43.6
...,...,...,...,...,...,...,...,...,...,...
955,2005,India,24.7,10.6,1.4,691,776502158,12.2,13,67.4
956,2005,India,34.8,15.8,1.3,1910,1287584579,12.4,1,51.9
979,2016,India,16.4,6.7,2.2,2436,1018037875,44.4,13,21.1
981,2005,India,17.4,2.0,4.2,1462,13350251,41.2,8,42.6
995,2019,India,23.6,8.0,1.2,1365,1358019778,10.0,8,20.2

In [84]:
df[df['CO2 Emissions (Tons/Capita)'] == df['CO2 Emissions (Tons/Capita)'].min()]

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
110,2009,Germany,6.3,0.5,1.1,1801,64317241,49.3,3,37.5
314,2002,USA,17.0,0.5,3.5,1184,84528761,7.3,14,21.4
613,2011,UK,19.6,0.5,3.3,1256,167459760,27.7,9,59.6
856,2018,Brazil,9.8,0.5,1.0,656,239135473,20.6,5,51.3

In [85]:
df[df['CO2 Emissions (Tons/Capita)'] == df['CO2 Emissions (Tons/Capita)'].max ()]

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
237,2015,Brazil,28.9,20.0,3.5,2017,1213528698,12.2,7,47.8
425,2012,China,12.7,20.0,4.1,2701,1014597705,46.0,11,57.3
707,2021,UK,17.1,20.0,5.0,2022,284705392,41.0,14,52.7

In [86]:
df.groupby('Country')['Avg Temperature (°C)'].mean()

Country
Argentina       19.298507
Australia       19.449123
Brazil          20.835821
Canada          20.011940
China           20.282090
France          19.383333
Germany         20.288525
India           19.764286
Indonesia       18.918667
Japan           20.453968
Mexico          20.696364
Russia          20.718919
South Africa    20.738356
UK              18.490769
USA             19.049315
Name: Avg Temperature (°C), dtype: float64

In [87]:
df[df['Population']>50000000].drop_duplicates('Country')

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
0,2006,UK,8.9,9.3,3.1,1441,530911230,20.4,14,59.8
1,2019,USA,31.0,4.8,4.2,2407,107364344,49.2,8,31.0
2,2014,France,33.9,2.8,2.2,1241,441101758,33.3,9,35.5
3,2010,Argentina,5.9,1.8,3.2,1892,1069669579,23.7,7,17.7
4,2007,Germany,26.9,5.6,2.4,1743,124079175,12.5,4,17.4
5,2020,China,32.3,1.4,2.7,2100,1202028857,49.4,12,47.2
7,2018,South Africa,33.9,6.0,4.5,827,83947380,17.7,1,56.6
9,2010,Australia,18.3,1.9,3.5,2599,849496137,7.5,5,48.7
10,2010,Indonesia,14.4,4.9,3.3,2466,1345958932,10.4,13,10.8
12,2020,Brazil,26.7,12.2,1.8,762,1106863791,46.8,0,69.1
15,2023,India,31.0,17.6,2.0,2444,365927452,25.1,8,20.6
19,2001,Canada,21.3,12.7,3.3,1944,1189649940,21.3,3,26.2
21,2011,Mexico,11.1,16.8,2.7,1099,250843348,8.2,5,33.4
30,2009,Japan,34.0,10.0,3.3,1598,176809981,44.9,1,27.9
35,2011,Russia,23.2,1.8,4.7,2157,1034642225,11.5,5,31.8

In [88]:
avg =df['Avg Temperature (°C)'].mean()
df[df['Avg Temperature (°C)']>avg]['Country']

1            USA
2         France
4        Germany
5          China
6      Argentina
         ...
995        India
996           UK
997    Argentina
998    Australia
999      Germany
Name: Country, Length: 508, dtype: object

In [89]:
df[['Country','Year','Population','CO2 Emissions (Tons/Capita)']]

       Country  Year  Population  CO2 Emissions (Tons/Capita)
0           UK  2006   530911230                          9.3
1          USA  2019   107364344                          4.8
2       France  2014   441101758                          2.8
3    Argentina  2010  1069669579                          1.8
4      Germany  2007   124079175                          5.6
..         ...   ...         ...                          ...
995      India  2019  1358019778                          8.0
996         UK  2000   876123161                         10.0
997  Argentina  2019  1120533308                          8.9
998  Australia  2016   380662109                         14.9
999    Germany  2011   398407112                         17.3

[1000 rows x 4 columns]

In [90]:
df[df['Population']>1000000000]

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
3,2010,Argentina,5.9,1.8,3.2,1892,1069669579,23.7,7,17.7
5,2020,China,32.3,1.4,2.7,2100,1202028857,49.4,12,47.2
10,2010,Indonesia,14.4,4.9,3.3,2466,1345958932,10.4,13,10.8
11,2023,South Africa,14.6,14.7,1.5,875,1311714067,31.1,14,19.7
12,2020,Brazil,26.7,12.2,1.8,762,1106863791,46.8,0,69.1
...,...,...,...,...,...,...,...,...,...,...
989,2011,UK,26.2,8.6,4.1,713,1287012541,17.9,9,20.6
993,2003,South Africa,30.2,8.5,2.9,1604,1168018187,28.7,3,33.9
994,2018,Australia,34.5,14.6,1.3,829,1211016796,7.6,6,27.1
995,2019,India,23.6,8.0,1.2,1365,1358019778,10.0,8,20.2
997,2019,Argentina,23.8,8.9,4.7,891,1120533308,25.9,10,46.5

In [91]:
df[df['Avg Temperature (°C)']>25]

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
1,2019,USA,31.0,4.8,4.2,2407,107364344,49.2,8,31.0
2,2014,France,33.9,2.8,2.2,1241,441101758,33.3,9,35.5
4,2007,Germany,26.9,5.6,2.4,1743,124079175,12.5,4,17.4
5,2020,China,32.3,1.4,2.7,2100,1202028857,49.4,12,47.2
6,2006,Argentina,30.7,11.6,3.9,1755,586706107,41.9,10,50.5
...,...,...,...,...,...,...,...,...,...,...
990,2004,Canada,34.2,0.8,3.6,2744,94344322,48.3,6,35.7
991,2005,Indonesia,29.8,6.3,4.3,518,431162461,19.1,3,17.6
992,2021,Indonesia,26.0,9.5,4.9,1141,916703921,9.4,10,44.0
993,2003,South Africa,30.2,8.5,2.9,1604,1168018187,28.7,3,33.9
994,2018,Australia,34.5,14.6,1.3,829,1211016796,7.6,6,27.1

In [92]:
CO2_mean = df['CO2 Emissions (Tons/Capita)'].mean()
df[(df['Population']>500000000)&(df['CO2 Emissions (Tons/Capita)']>CO2_mean)]

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
6,2006,Argentina,30.7,11.6,3.9,1755,586706107,41.9,10,50.5
8,2022,UK,27.8,16.6,1.5,1966,980305187,8.2,4,43.4
11,2023,South Africa,14.6,14.7,1.5,875,1311714067,31.1,14,19.7
12,2020,Brazil,26.7,12.2,1.8,762,1106863791,46.8,0,69.1
14,2007,Germany,11.0,17.6,1.7,2906,1179622755,42.9,3,50.7
...,...,...,...,...,...,...,...,...,...,...
974,2010,Brazil,5.0,15.8,5.0,2329,909090341,21.0,12,32.9
982,2018,Indonesia,29.1,16.7,1.9,1382,1160732321,43.3,10,52.7
984,2014,USA,5.5,10.7,3.2,1015,560097732,42.2,2,50.4
985,2010,Brazil,17.6,16.0,3.1,1920,584023989,18.7,4,52.3
994,2018,Australia,34.5,14.6,1.3,829,1211016796,7.6,6,27.1

In [93]:
sea_mean = df['Sea Level Rise (mm)'].mean()
df[(df['Sea Level Rise (mm)']>avg)&(df['Avg Temperature (°C)']<10)]

Empty DataFrame
Columns: [Year, Country, Avg Temperature (°C), CO2 Emissions (Tons/Capita), Sea Level Rise (mm), Rainfall (mm), Population, Renewable Energy (%), Extreme Weather Events, Forest Area (%)]
Index: []

In [94]:
df[df['Year']<2020]

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
0,2006,UK,8.9,9.3,3.1,1441,530911230,20.4,14,59.8
1,2019,USA,31.0,4.8,4.2,2407,107364344,49.2,8,31.0
2,2014,France,33.9,2.8,2.2,1241,441101758,33.3,9,35.5
3,2010,Argentina,5.9,1.8,3.2,1892,1069669579,23.7,7,17.7
4,2007,Germany,26.9,5.6,2.4,1743,124079175,12.5,4,17.4
...,...,...,...,...,...,...,...,...,...,...
995,2019,India,23.6,8.0,1.2,1365,1358019778,10.0,8,20.2
996,2000,UK,21.8,10.0,2.2,1273,876123161,14.9,14,30.1
997,2019,Argentina,23.8,8.9,4.7,891,1120533308,25.9,10,46.5
998,2016,Australia,21.0,14.9,3.1,1136,380662109,24.5,3,44.5
999,2011,Germany,24.1,17.3,2.1,2854,398407112,41.0,3,19.8

In [95]:
df.groupby('Country')['Population'].max()

Country
Argentina       1356785799
Australia       1388230143
Brazil          1393981934
Canada          1395185778
China           1358197397
France          1379671819
Germany         1377569278
India           1366390185
Indonesia       1358606331
Japan           1385374585
Mexico          1388289771
Russia          1397016073
South Africa    1383289354
UK              1387457528
USA             1380798693
Name: Population, dtype: int64

In [96]:
df.groupby('Country')['Avg Temperature (°C)'].min()

Country
Argentina       5.7
Australia       5.4
Brazil          5.0
Canada          5.5
China           5.4
France          5.1
Germany         5.1
India           5.3
Indonesia       5.5
Japan           5.7
Mexico          5.1
Russia          5.3
South Africa    5.0
UK              5.0
USA             5.5
Name: Avg Temperature (°C), dtype: float64

In [97]:
df.groupby('Country')['CO2 Emissions (Tons/Capita)'].mean()

Country
Argentina       10.447761
Australia        8.900000
Brazil          10.838806
Canada          10.113433
China           10.835821
France          10.966667
Germany          9.880328
India           10.694286
Indonesia       11.021333
Japan           10.960317
Mexico           9.347273
Russia           8.967568
South Africa     9.617808
UK              12.650769
USA             10.882192
Name: CO2 Emissions (Tons/Capita), dtype: float64

In [98]:
df['Country'].nunique()

15

In [99]:
df.groupby('Country')['Sea Level Rise (mm)'].mean()

Country
Argentina       3.168657
Australia       3.164912
Brazil          3.174627
Canada          3.138806
China           2.932836
France          3.193939
Germany         2.870492
India           2.901429
Indonesia       2.753333
Japan           3.076190
Mexico          2.689091
Russia          3.287838
South Africa    2.890411
UK              2.958462
USA             2.926027
Name: Sea Level Rise (mm), dtype: float64

In [100]:
df.head()

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
0,2006,UK,8.9,9.3,3.1,1441,530911230,20.4,14,59.8
1,2019,USA,31.0,4.8,4.2,2407,107364344,49.2,8,31.0
2,2014,France,33.9,2.8,2.2,1241,441101758,33.3,9,35.5
3,2010,Argentina,5.9,1.8,3.2,1892,1069669579,23.7,7,17.7
4,2007,Germany,26.9,5.6,2.4,1743,124079175,12.5,4,17.4

In [101]:
df.groupby('Country')['Forest Area (%)'].mean()

Country
Argentina       38.832836
Australia       40.852632
Brazil          39.774627
Canada          41.932836
China           44.302985
France          39.496970
Germany         42.598361
India           38.990000
Indonesia       40.524000
Japan           38.120635
Mexico          43.376364
Russia          38.509459
South Africa    41.072603
UK              42.718462
USA             38.534247
Name: Forest Area (%), dtype: float64

In [102]:
df.sort_values(by=['Population'],ascending=True)

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
838,2010,China,30.9,12.1,2.0,2915,3660891,17.0,5,62.1
732,2021,Japan,16.1,3.6,4.3,991,5467801,25.7,7,29.9
251,2017,Brazil,7.7,18.2,1.2,1579,9355425,27.1,8,61.0
575,2003,India,6.4,9.4,3.8,1573,9918562,28.9,7,36.8
853,2002,Indonesia,5.5,11.9,4.6,1605,10978954,18.3,5,31.0
...,...,...,...,...,...,...,...,...,...,...
344,2020,Brazil,14.1,3.3,2.1,1573,1391047250,31.1,5,26.3
622,2017,Canada,16.3,2.3,3.4,2458,1391480145,17.1,9,63.9
341,2016,Brazil,28.1,16.9,4.9,934,1393981934,26.9,12,43.3
37,2019,Canada,21.8,1.0,4.9,2524,1395185778,5.8,1,51.0
700,2007,Russia,24.9,12.4,4.3,1450,1397016073,39.7,12,66.5

In [103]:
df.sort_values(by='Sea Level Rise (mm)')

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
742,2000,Mexico,25.6,3.3,1.0,2370,563852853,11.5,13,63.6
207,2001,UK,25.6,16.8,1.0,674,183851069,27.6,3,46.2
856,2018,Brazil,9.8,0.5,1.0,656,239135473,20.6,5,51.3
857,2020,Russia,12.7,3.9,1.0,1234,278429462,38.6,12,44.0
311,2023,Argentina,22.4,4.4,1.0,2857,94830920,49.5,11,44.2
...,...,...,...,...,...,...,...,...,...,...
448,2000,Indonesia,20.0,18.7,5.0,875,938024200,23.0,0,33.5
901,2002,India,8.5,0.8,5.0,1857,986237569,29.5,0,53.8
904,2013,Argentina,34.7,7.4,5.0,698,785566655,9.4,0,31.6
813,2000,Russia,15.1,15.8,5.0,1138,242436875,37.6,1,52.4
872,2012,South Africa,18.2,18.8,5.0,2885,90703756,30.0,3,53.9

Q3
Find countries where Renewable Energy (%) is greater than Forest Area (%).

In [104]:
df[df['Renewable Energy (%)'] > df['Forest Area (%)']]['Country']

1               USA
3         Argentina
5             China
11     South Africa
13              USA
           ...
983       Australia
988          Canada
990          Canada
991       Indonesia
999         Germany
Name: Country, Length: 295, dtype: object

Q4

Display all countries whose rainfall is between 800 mm and 1200 mm.

In [105]:
df[(df['Rainfall (mm)']>800) & (df['Rainfall (mm)']<1200)]

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
7,2018,South Africa,33.9,6.0,4.5,827,83947380,17.7,1,56.6
11,2023,South Africa,14.6,14.7,1.5,875,1311714067,31.1,14,19.7
21,2011,Mexico,11.1,16.8,2.7,1099,250843348,8.2,5,33.4
25,2000,India,20.9,15.9,2.6,1100,1237433800,26.4,8,61.3
26,2011,Australia,5.5,11.7,4.0,880,966063065,41.7,5,40.9
...,...,...,...,...,...,...,...,...,...,...
984,2014,USA,5.5,10.7,3.2,1015,560097732,42.2,2,50.4
992,2021,Indonesia,26.0,9.5,4.9,1141,916703921,9.4,10,44.0
994,2018,Australia,34.5,14.6,1.3,829,1211016796,7.6,6,27.1
997,2019,Argentina,23.8,8.9,4.7,891,1120533308,25.9,10,46.5
998,2016,Australia,21.0,14.9,3.1,1136,380662109,24.5,3,44.5

 Q7

Find the top 3 countries every year based on population.

In [114]:
 df.groupby('Year').apply(lambda x : x.sort_values(by='Population',ascending=False).head(3))

C:\Users\BHARAT\AppData\Local\Temp\ipykernel_24536\2207331437.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Year').apply(lambda x : x.sort_values(by='Population',ascending=False).head(3))

          Year       Country  Avg Temperature (°C)  \
Year
2000 456  2000     Australia                  11.4
     731  2000           USA                  12.1
     94   2000            UK                  22.9
2001 743  2001       Germany                  34.7
     73   2001  South Africa                  34.3
...        ...           ...                   ...
2022 357  2022         Japan                  10.4
     558  2022           USA                  29.3
2023 659  2023        Canada                  23.4
     877  2023         Japan                  27.7
     851  2023     Indonesia                  27.8

          CO2 Emissions (Tons/Capita)  Sea Level Rise (mm)  Rainfall (mm)  \
Year
2000 456                          2.2                  1.8           1071
     731                          9.3                  1.9           2051
     94                          13.7                  4.7           1255
2001 743                          4.7                  4.4           1504
     73                           9.7                  2.9           1241
...                               ...                  ...            ...
2022 357                          4.8                  1.1           2127
     558                         11.4                  4.5           2756
2023 659                          4.5                  3.8            971
     877                          4.7                  1.1           1286
     851                          9.3                  1.5           2648

          Population  Renewable Energy (%)  Extreme Weather Events  \
Year
2000 456  1388230143                  12.0                       4
     731  1380798693                  45.0                      14
     94   1366969728                  33.4                      12
2001 743  1377569278                  24.9                       0
     73   1356204695                  27.0                      13
...              ...                   ...                     ...
2022 357  1360173043                  21.8                       6
     558  1339427830                  25.5                       9
2023 659  1380296219                   7.5                       5
     877  1368121693                  18.9                       1
     851  1330131634                  19.4                      10

          Forest Area (%)
Year
2000 456             50.9
     731             14.2
     94              41.2
2001 743             36.9
     73              51.3
...                   ...
2022 357             25.9
     558             34.5
2023 659             28.2
     877             53.6
     851             17.2

[72 rows x 10 columns]

Q8

Find the bottom 5 countries every year based on forest area.

In [117]:
df.groupby('Year',group_keys=False).apply(lambda x : x.sort_values(by='Forest Area (%)',ascending=True).head(5))

C:\Users\BHARAT\AppData\Local\Temp\ipykernel_24536\762575639.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Year',group_keys=False).apply(lambda x : x.sort_values(by='Forest Area (%)',ascending=True).head(5))

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
631,2000,South Africa,34.8,8.6,1.9,2236,824102127,10.2,2,11.1
731,2000,USA,12.1,9.3,1.9,2051,1380798693,45.0,14,14.2
951,2000,Germany,14.4,0.7,1.3,2904,1357011909,30.8,5,15.6
508,2000,South Africa,24.0,14.3,1.7,2762,313096322,17.5,6,17.1
769,2000,India,32.3,6.5,1.2,1066,211473371,36.8,8,17.5
...,...,...,...,...,...,...,...,...,...,...
898,2023,Argentina,29.0,18.3,4.5,2435,536217615,25.7,8,10.3
97,2023,USA,6.2,18.6,4.4,1806,487618104,21.9,8,12.1
698,2023,Mexico,11.5,8.6,1.8,582,866432043,8.8,3,13.2
823,2023,France,21.4,11.2,4.9,926,343707677,36.5,13,15.5
851,2023,Indonesia,27.8,9.3,1.5,2648,1330131634,19.4,10,17.2

Q9

Display the country with the highest CO₂ emission for every year.

In [119]:
df.groupby('Year').apply(lambda x : x.sort_values(by='CO2 Emissions (Tons/Capita)').head(1))

C:\Users\BHARAT\AppData\Local\Temp\ipykernel_24536\354355173.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Year').apply(lambda x : x.sort_values(by='CO2 Emissions (Tons/Capita)').head(1))

,,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
Year,,,,,,,,,,,
2000,951,2000,Germany,14.4,0.7,1.3,2904,1357011909,30.8,5,15.6
2001,330,2001,India,20.8,1.0,3.8,2112,42474142,23.5,1,29.3
2002,314,2002,USA,17.0,0.5,3.5,1184,84528761,7.3,14,21.4
2003,288,2003,USA,12.4,0.6,3.5,2780,866033515,14.2,11,44.6
2004,990,2004,Canada,34.2,0.8,3.6,2744,94344322,48.3,6,35.7
2005,863,2005,Indonesia,7.8,0.6,2.3,654,673431694,10.9,14,56.3
2006,113,2006,Brazil,24.6,1.3,2.5,2815,69840394,31.4,12,15.6
2007,63,2007,Japan,15.4,1.3,4.3,921,194923647,31.5,3,45.1
2008,181,2008,Russia,12.6,0.6,3.8,678,1184550275,47.0,14,67.5
2009,110,2009,Germany,6.3,0.5,1.1,1801,64317241,49.3,3,37.5
2010,169,2010,Australia,16.9,1.0,3.5,1973,373401883,47.9,7,23.5
2011,613,2011,UK,19.6,0.5,3.3,1256,167459760,27.7,9,59.6
2012,636,2012,Argentina,21.3,1.0,3.8,656,449021301,37.5,12,11.1
2013,716,2013,Argentina,23.0,0.9,3.0,897,1152666411,40.7,7,48.6
2014,792,2014,Brazil,6.4,0.9,3.3,725,558731629,46.4,7,57.4
2015,336,2015,USA,28.8,0.6,2.2,2382,204172325,9.9,8,27.5
2016,819,2016,Brazil,26.6,0.7,2.4,1492,83325440,12.7,7,38.8
2017,62,2017,South Africa,11.3,0.6,3.0,1005,941922654,41.6,3,40.3
2018,856,2018,Brazil,9.8,0.5,1.0,656,239135473,20.6,5,51.3
2019,37,2019,Canada,21.8,1.0,4.9,2524,1395185778,5.8,1,51.0
2020,756,2020,Australia,28.5,0.8,4.0,628,1103288537,13.3,7,54.9
2021,485,2021,Japan,31.3,2.0,3.5,883,606697131,22.5,1,21.1
2022,690,2022,Argentina,27.7,0.7,1.9,1954,1096617947,21.7,13,32.7
2023,947,2023,USA,12.6,1.1,1.9,1594,572998076,8.9,0,63.9